export const PROFILE_FETCH_REQUEST = 'PROFILE_FETCH_REQUEST'
export const PROFILE_FETCH_SUCCESS = 'PROFILE_FETCH_SUCCESS'
export const PROFILE_FETCH_FAIL = 'PROFILE_FETCH_FAIL'
export const PROFILE_FETCH_RESET = 'PROFILE_FETCH_RESET'