export const REPORT_FETCH_REQUEST = 'REPORT_FETCH_REQUEST'
export const REPORT_FETCH_SUCCESS = 'REPORT_FETCH_SUCCESS'
export const REPORT_FETCH_FAIL = 'REPORT_FETCH_FAIL'
export const REPORT_FETCH_RESET = 'REPORT_FETCH_RESET'