export const REPORTER_FETCH_REQUEST = 'REPORTER_FETCH_REQUEST'
export const REPORTER_FETCH_SUCCESS = 'REPORTER_FETCH_SUCCESS'
export const REPORTER_FETCH_FAIL = 'REPORTER_FETCH_FAIL'
export const REPORTER_FETCH_RESET = 'REPORTER_FETCH_RESET'